version: '2'
services:
 opengts:
  container_name: opengts
  image: halilintar8/opengts
  ports:
   - 8080:8080
  environment:
   - MYSQL_ROOT_PASSWORD=mysqlroot
   - MYSQL_DBNAME=gts
   - MYSQL_DBPASS=opengts
   - MYSQL_DBUSER=gts
   - CREATE_DATABASE=true
   - SYSADMIN_PASSWORD=sysadmin
   - MYSQL_SERVICE_HOST=mysql
 mysql:
  container_name: mysql
  image: mariadb
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=mysqlroot
   - MYSQL_DBNAME=gts
   - MYSQL_DBPASS=opengts
   - MYSQL_DBUSER=gts
   - CREATE_DATABASE=true